version: '3'
services:
    viscoin:
        container_name: viscoin
        restart: always
        build: .
        network_mode: host
        env_file:
            - .env
        volumes:
            - ./db:/viscoin/db
